# This is a basic workflow to help you get started with Actions

name: CI (RC)

# Controls when the workflow will run
on:
  # Triggers the workflow on push, for untagged commits
  push:
    branches:
      - "main"
    tags-ignore:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Get current date
      id: date
      run: echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

    - name: Install dependencies
      id: deps
      run: |
        mkdir -p "001 Dependencies/ahuyn/"
        mkdir -p "001 Dependencies/arm/"

        cp -r anomaly-dependencies/trader_autoinject/gamedata "001 Dependencies/ahuyn/"
        cp -r anomaly-addon-deps/AnomalyRadialMenu/gamedata "001 Dependencies/arm/"

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'HideoutFurniture-${{ env.DATE }}.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig /*anomaly-dependencies/* /*anomaly-addon-deps/*'

    - name: Upload Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        files: "HideoutFurniture-${{ env.DATE }}.zip"
        automatic_release_tag: "latest"
        title: "pre-release"
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        id: "automatic_releases"